import { readdirSync, readFileSync } from "node:fs"
import { join } from "node:path"
import { createStore } from "@/store"
import { importProblemBundle, parseProblemBundle } from "./problem-export"
import { resolveDimensionLabel } from "@/lib/dimension-labels"
import { loadResearchCapture } from "@/lib/research-capture"
import { getIdentifyLens } from "@/data/reflectLenses"
import { getResearchMethod } from "@/data/researchMethods"

/**
 * The example projects in `examples/` are generated by
 * `scripts/make-example-projects.mjs` and handed to people to import. They are
 * only useful if they actually import, so this walks every file through the
 * real parse-and-import path and checks that nothing in them has gone stale.
 *
 * Every id in a bundle has to resolve against the catalogue it came from, and
 * all of them fail quietly rather than loudly: a renamed dimension slug
 * renders as "(deleted item)", a lens the hub no longer offers sends the
 * journey rail to the hub instead of the tool, and a capture keyed by prompt
 * ids its method does not have pre-fills as blank when the tool is revisited.
 */
const DIR = join(process.cwd(), "examples")
const files = readdirSync(DIR).filter((f) => f.endsWith(".navigate.json"))

it("has example files to check", () => {
  expect(files.length).toBeGreaterThan(0)
})

it.each(files)("imports %s", async (file) => {
  // Each case starts from an empty library, or the models hydrate from what
  // the previous import left behind and the counts accumulate.
  localStorage.clear()
  const bundle = parseProblemBundle(readFileSync(join(DIR, file), "utf8"))
  const store = createStore()
  for (const init of [
    store.dispatch.projects.init, store.dispatch.problems.init, store.dispatch.solutions.init,
    store.dispatch.solutionWorkspaces.init, store.dispatch.customDimensionItems.init,
    store.dispatch.selfDiscoveryItems.init, store.dispatch.reflectSessions.init,
    store.dispatch.researchSessions.init, store.dispatch.canvasDrafts.init,
    store.dispatch.solutionComparison.init,
  ]) init()

  const result = await importProblemBundle(bundle, store.dispatch)
  const state = store.getState()
  const problem = state.problems.problems.find((p) => p.id === result.problemId)!
  const labels = (column: string, ids: string[]) =>
    ids.map((id) => resolveDimensionLabel(column, id, state.customDimensionItems.byColumn, state.selfDiscoveryItems.items))

  expect([
    ...labels("customers", problem.customers),
    ...labels("contexts", problem.contexts),
    ...labels("problems", problem.problems),
    ...labels("you", problem.you),
  ]).not.toContain("(deleted item)")
  expect(state.solutions.solutions).toHaveLength(bundle.solutions.length)

  // The lens a guided prompt tool captured, with its answers under that lens's
  // own prompt ids, or the tool cannot pre-fill when the problem is revisited.
  if (problem.reflection) {
    const lens = getIdentifyLens(problem.reflection.lensId)
    expect(lens, `unknown lens ${problem.reflection.lensId}`).toBeDefined()
    const promptIds = lens!.prompts.map((p) => p.id)
    for (const entry of problem.reflection.prompts) {
      expect(promptIds, `unknown prompt ${entry.promptId} on lens ${lens!.id}`).toContain(entry.promptId)
    }
  }

  // The same for Research, whose capture is kept beside the problem.
  const capture = loadResearchCapture(problem.id)
  if (capture) {
    const method = getResearchMethod(capture.methodId)
    expect(method, `unknown research method ${capture.methodId}`).toBeDefined()
    if (capture.toolId !== null) {
      expect(method!.tools.map((t) => t.id), `unknown tool ${capture.toolId}`).toContain(capture.toolId)
    }
    const promptIds = method!.prompts.map((p) => p.id)
    for (const entry of capture.prompts) {
      expect(promptIds, `unknown prompt ${entry.promptId} on ${method!.id}`).toContain(entry.promptId)
    }
  }

  // A capture only exists because that tool saved the problem, so its source
  // has to agree: anything else is data the app would never have written.
  expect(capture === null || problem.source === "research").toBe(true)
  expect(problem.reflection === null || problem.source === "reflect" || problem.source === "identify").toBe(true)
})
